import arrowLeftRight from "./assets/images/arow-left-right.png"

export const links = [
  { path: "", text: "home" },
  { path: ".", text: "models" },
  { path: "faqs", text: "faqs" },
  { path: "affiliate-partner", text: "affiliate partner" },
  { path: "contact-us", text: "contact us" },
  { path: "client-area", text: "client area" },
]

export const exchange = [
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
  {
    currency_name: "EUR",
    country_code: "USD",
    arrow_left_right_img: arrowLeftRight,
    price_iniate: "$1.06199",
    price_final: "$1.06199",
    rate: "+0.06%",
  },
]
